### ISSUE TITLE
Distorted extractions

### ISSUE THREAD

**Issue by sayyid5416** [hussain5416/Extract_Links#7]
![image](https://user-images.githubusercontent.com/78584556/107152816-09780600-6990-11eb-8ba0-21b0538100dd.png)

**Comment by sayyid5416** [comment]
File to reproduce: [test.txt](https://github.com/hussain5416/Extract_Links/files/5939421/test.txt)

**Comment by hussain5416** [comment]
Fixed

**Comment by sayyid5416** [comment]
Will be fixed in [v1.2](https://github.com/hussain5416/Extract_Links/milestone/3)
